(ns ix.test
  (:require 
   [ix.omut.common_input]
   [ix.omut.component.actions_modal]
   [ix.omut.component.actions_modal_button]
   [ix.omut.component.alert]
   [ix.omut.component.edit_form_for_id]
   [ix.omut.component.file]
   [ix.omut.component.file_uploder]
   [ix.omut.component.helper_p]
   [ix.omut.component.image_full_screen_viewer]
   [ix.omut.component.images_and_files_btn_viewer]
   [ix.omut.component.images_gallery_1]
   [ix.omut.component.input]
   [ix.omut.component.input_change_password]
   [ix.omut.component.input_datetime]
   [ix.omut.component.input_select_checkboxes]
   [ix.omut.component.message_modal]
   [ix.omut.component.modal]
   [ix.omut.component.modal_edit_form_for_id__close]
   [ix.omut.component.modal_edit_form_for_id__yes_no]
   [ix.omut.component.modal_yes_no]
   [ix.omut.component.nav]
   [ix.omut.component.nav_tabs]
   [ix.omut.component.one_image_uploder]
   [ix.omut.component.paginator]
   [ix.omut.component.search_view]
   [ix.omut.component.select]
   [ix.omut.component.tbody_trs_sel]
   [ix.omut.component.text_collapser]
   [ix.omut.component.textarea]
   [ix.omut.component.thumbinal]
   [ix.omut.component.thumbinal_edit_form]
   [ix.omut.component.thumbinal_modal_edit_form]
   [ix.omut.component.toggle_button]
   [ix.omut.component.tr_sel]
   [ix.omut.core]
   [ix.omut.input_from_search]
   [ix.omut.ui.button]
   [ix.omut.ui.cdate_udate]
   [ix.omut.ui.collapser]
   [ix.omut.ui.container]
   [ix.omut.ui.container_fluid]
   [ix.omut.ui.datatime]
   [ix.omut.ui.form_group]
   [ix.omut.ui.glyphicon]
   [ix.omut.ui.label]
   [ix.omut.ui.list_group]
   [ix.omut.ui.list_group__counts_by]
   [ix.omut.ui.list_group_item]
   [ix.omut.ui.media]
   [ix.omut.ui.media_object]
   [ix.omut.ui.nav]
   [ix.omut.ui.nav_tab]
   [ix.omut.ui.navbar_li_dropdown]
   [ix.omut.ui.navbar_li_separator]
   [ix.omut.ui.panel]
   [ix.omut.ui.panel_with_table]
   [ix.omut.ui.row]
   [ix.omut.ui.table]
   [ix.omut.ui.tbody]
   [ix.omut.ui.thead_tr]
   [ix.omut.ui.ul_navbar_nav]
   [ix.omut.ui.virtual_pages]
   ))


(println 1111)



